version: '3.9'
services:
  app:
    container_name: vue-xzdwq-dev
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    command: npm run dev
    restart: always
    ports:
      - 4445:4444
      - 8081:8081
    volumes:
      - ../../:/app
      - nodemodules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  nodemodules: {}
